#!/usr/bin/env python3
import pandas as pd
import os
from pathlib import Path
import fnmatch
from utils.utils import *
from concurrent.futures import ProcessPoolExecutor, as_completed
import multiprocessing


mtl_modules = [
    "Control.Monad.Cont",
    "Control.Monad.Cont.Class",
    "Control.Monad.Error",
    "Control.Monad.Error.Class",
    "Control.Monad.Except",
    "Control.Monad.Identity",
    "Control.Monad.List",
    "Control.Monad.RWS",
    "Control.Monad.RWS.Class",
    "Control.Monad.RWS.Lazy",
    "Control.Monad.RWS.Strict",
    "Control.Monad.Reader",
    "Control.Monad.Reader.Class",
    "Control.Monad.State",
    "Control.Monad.State.Class",
    "Control.Monad.State.Lazy",
    "Control.Monad.State.Strict",
    "Control.Monad.Trans",
    "Control.Monad.Writer",
    "Control.Monad.Writer.Class",
    "Control.Monad.Writer.Lazy",
    "Control.Monad.Writer.Strict",
    "Control.Monad.Trans",
    "Control.Monad.Trans.Class",
]
transfromers_modules = [
    "Control.Monad.Trans.Accum",
    "Control.Monad.Trans.Class",
    "Control.Monad.Trans.Cont",
    "Control.Monad.Trans.Except",
    "Control.Monad.Trans.Identity",
    "Control.Monad.Trans.Maybe",
    "Control.Monad.Trans.RWS",
    "Control.Monad.Trans.RWS.CPS",
    "Control.Monad.Trans.RWS.Lazy",
    "Control.Monad.Trans.RWS.Strict",
    "Control.Monad.Trans.Reader",
    "Control.Monad.Trans.Select",
    "Control.Monad.Trans.State",
    "Control.Monad.Trans.State.Lazy",
    "Control.Monad.Trans.State.Strict",
    "Control.Monad.Trans.Writer",
    "Control.Monad.Trans.Writer.CPS",
    "Control.Monad.Trans.Writer.Lazy",
    "Control.Monad.Trans.Writer.Strict"
]
other_modules = [
    "Control.Monad", 
    "System.IO",
    "Control.Monad.Trans.Control",
    "Control.Monad.Free",
    "Control.Monad.Free.Ap",
    "Control.Monad.Free.Church",
    "Control.Monad.Free.Class",
    "Control.Monad.Free.TH"
]
ALL_MONAD_MODULES = mtl_modules + transfromers_modules + other_modules

## this portion was generated by deepseek ai
def process_file_for_monads(args):
    """
    Worker function for parallel processing.
    Gets imports for a single file and determines monad usage.
    """
    file_path, package_root, cabal_file, package_name, version, lts = args
    
    # Get imports for this file
    imports = get_file_imports(file_path, package_root, cabal_file)
    
    # Create result dict with basic info
    result = {
        'package_name': package_name,
        'version': version,
        'lts': lts,
        'file_path': file_path,
        'imports': imports,
    }
    
    # Add monad flags (0 or 1 for each monad)
    imports_set = set(imports)
    for monad in ALL_MONAD_MODULES:
        result[monad] = 1 if monad in imports_set else 0
    
    return result

def add_monad_columns_to_files_parallel(files_df, packages_df, lts, max_workers=None):
    """
    Add monad columns to files DataFrame using parallel processing.
    """
    # Make a copy and remove any existing monad columns
    files_df = files_df.copy()
    existing_monad_cols = [c for c in files_df.columns if c in ALL_MONAD_MODULES]
    if existing_monad_cols:
        print(f"  Removing {len(existing_monad_cols)} existing monad columns...")
        files_df = files_df.drop(columns=existing_monad_cols)
    
    # ... rest of the function
    if max_workers is None:
        max_workers = multiprocessing.cpu_count()
    
    print(f"  🔄 Processing {len(files_df)} files with {max_workers} workers...")
    
    # Prepare arguments for each file
    tasks = []
    for idx, row in files_df.iterrows():
        package_name = row['package_name']
        version = row['version']
        file_path = row['file_path']
        
        # Get package info from packages DataFrame
        pkg_info = packages_df[packages_df['package'] == package_name]
        if len(pkg_info) == 0:
            continue
        
        cabal_file = pkg_info.iloc[0].get('cabal-file', '')
        if not cabal_file or pd.isna(cabal_file):
            continue
        
        package_root = os.path.dirname(cabal_file)
        
        tasks.append((file_path, package_root, cabal_file, package_name, version, lts))
    
    print(f"  📋 Prepared {len(tasks)} tasks")
    
    # Process files in parallel
    results = []
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        # Submit all tasks
        future_to_task = {executor.submit(process_file_for_monads, task): task for task in tasks}
        
        # Collect results as they complete
        completed = 0
        for future in as_completed(future_to_task):
            completed += 1
            if completed % 100 == 0:
                print(f"    Processed {completed}/{len(tasks)} files...")
            try:
                result = future.result()
                results.append(result)
            except Exception as e:
                print(f"    ❌ Error processing file: {e}")
    
    # Convert results to DataFrame
    result_df = pd.DataFrame(results)
    
    # Merge back with original files_df
    enhanced_df = files_df.merge(
        result_df[['file_path', 'package_name', 'imports'] + ALL_MONAD_MODULES],
        on=['file_path', 'package_name'],
        how='left'
    )
    
    # Fill NaN with 0 for monad columns
    for monad in ALL_MONAD_MODULES:
        if monad in enhanced_df.columns:
            enhanced_df[monad] = enhanced_df[monad].fillna(0).astype(int)
    
    return enhanced_df

def process_all_lts_with_monads():
    """
    Process all LTS versions and add file-level monad columns.
    Includes checkpointing to resume after crashes.
    """
    lts_list = get_lts_list_from_csv()
    print(f"Found {len(lts_list)} LTS versions in CSV:")
    print("="*60)
    
    results = []
    
    # Track which LTS versions are already done
    checkpoint_file = 'monad_processing_checkpoint.txt'
    completed_lts = []
    if os.path.exists(checkpoint_file):
        with open(checkpoint_file, 'r') as f:
            completed_lts = [line.strip() for line in f.readlines()]
        print(f"📋 Found checkpoint: {len(completed_lts)} LTS versions already processed")
    
    for i, lts in enumerate(lts_list, 1):
        # Skip if already completed
        if lts in completed_lts:
            print(f"\n[{i}/{len(lts_list)}] ⏭️ Skipping LTS {lts} (already processed)")
            continue
            
        print(f"\n[{i}/{len(lts_list)}] Processing LTS {lts}...")
        
        try:
            # Check if files DataFrame exists
            files_path = f'../data/dfs/lts-{lts}/lts-{lts}-files.df'
            if not os.path.exists(files_path):
                print(f"  ⚠️ Files DataFrame not found, skipping")
                results.append({'lts': lts, 'status': 'skipped', 'reason': 'files_df_missing'})
                continue
            
            # Load files DataFrame
            files_df = pd.read_pickle(files_path)
            print(f"  📁 Loaded {len(files_df)} files")
            
            # Load packages DataFrame
            pkg_path = f'../data/dfs/lts-{lts}/lts-{lts}.df'
            packages_df = pd.read_pickle(pkg_path)
            
            # Check if monad columns already exist
            existing_monad_cols = [c for c in files_df.columns if c in ALL_MONAD_MODULES]
            if existing_monad_cols:
                print(f"  ⏭️ Monad columns already exist ({len(existing_monad_cols)} found)")
                results.append({'lts': lts, 'status': 'skipped', 'reason': 'monads_exist'})
                # Mark as completed even if skipped (since they already have monads)
                with open(checkpoint_file, 'a') as f:
                    f.write(f"{lts}\n")
                continue
            
            # Add monad columns with parallel processing
            print(f"  🔄 Processing with {multiprocessing.cpu_count()} workers...")
            enhanced_df = add_monad_columns_to_files_parallel(files_df, packages_df, lts)
            
            # Save back to disk
            enhanced_df.to_pickle(files_path)
            
            monad_count = len([c for c in enhanced_df.columns if c in ALL_MONAD_MODULES])
            files_with_monads = enhanced_df[(enhanced_df[[c for c in enhanced_df.columns if c in ALL_MONAD_MODULES]] == 1).any(axis=1)].shape[0]
            
            print(f"  ✅ Added {monad_count} monad columns to {len(enhanced_df)} files")
            print(f"  📊 {files_with_monads} files have monad imports ({files_with_monads/len(enhanced_df)*100:.1f}%)")
            
            results.append({
                'lts': lts,
                'status': 'success',
                'files': len(enhanced_df),
                'monad_columns': monad_count,
                'files_with_monads': files_with_monads
            })
            
            # Save checkpoint
            with open(checkpoint_file, 'a') as f:
                f.write(f"{lts}\n")
            
        except Exception as e:
            print(f"  ❌ Error processing LTS {lts}: {e}")
            import traceback
            traceback.print_exc()
            results.append({'lts': lts, 'status': 'error', 'error': str(e)})
            # Don't mark as completed, so it will retry next time
    
    # Summary
    print("\n" + "="*60)
    print("PROCESSING SUMMARY")
    print("="*60)
    
    success = [r for r in results if r['status'] == 'success']
    skipped = [r for r in results if r['status'] == 'skipped']
    errors = [r for r in results if r['status'] == 'error']
    
    print(f"✅ Successful: {len(success)}")
    print(f"⏭️ Skipped: {len(skipped)}")
    print(f"❌ Errors: {len(errors)}")
    
    if success:
        print("\n📊 Successful LTS versions:")
        for r in success:
            print(f"   LTS {r['lts']}: {r['files']} files, {r['monad_columns']} monad cols, {r['files_with_monads']} with monads ({r['files_with_monads']/r['files']*100:.1f}%)")
    
    if errors:
        print("\n❌ Failed LTS versions:")
        for r in errors:
            print(f"   LTS {r['lts']}: {r['error']}")
        print("\n💡 To retry failed LTS versions, run again and they will be re-processed.")
    
    return results
    
    # check_processed.py
import os
from pathlib import Path

def check_processed_lts():
    """Check which LTS versions already have monad columns"""
    data_path = Path('../data/dfs')
    lts_folders = [f.name.replace('lts-', '') for f in data_path.glob('lts-*') if f.is_dir()]
    lts_folders = sorted(lts_folders, key=lambda x: [int(i) for i in x.split('-')])
    
    processed = []
    for lts in lts_folders:
        files_path = f'../data/dfs/lts-{lts}/lts-{lts}-files.df'
        if os.path.exists(files_path):
            try:
                df = pd.read_pickle(files_path)
                monad_cols = [c for c in df.columns if 'Control.Monad' in c]
                if monad_cols:
                    processed.append(lts)
            except:
                pass
    
    print(f"📊 LTS versions with monad columns: {len(processed)}")
    print(f"   {processed[:10]}...")
    return processed


def clean_duplicates(lts):
    """Remove duplicate columns from files DataFrame"""
    files_path = f'../data/dfs/lts-{lts}/lts-{lts}-files.df'
    if not os.path.exists(files_path):
        return False
    
    df = pd.read_pickle(files_path)
    duplicates = df.columns[df.columns.duplicated()].tolist()
    
    if duplicates:
        print(f"  🧹 LTS {lts}: Removing {len(duplicates)} duplicates: {duplicates}")
        df = df.loc[:, ~df.columns.duplicated(keep='first')]
        df.to_pickle(files_path)
        return True
    return False

def clean_all_lts():
    """Clean duplicates from all LTS versions"""
    lts_list = get_lts_list_from_csv()
    print(f"🧹 Cleaning duplicates for {len(lts_list)} LTS versions...")
    
    cleaned = 0
    for lts in lts_list:
        if clean_duplicates(lts):
            cleaned += 1
    
    print(f"✅ Cleaned {cleaned} LTS versions")

# Run everything
# process_all_lts()           # Create files DataFrames (if needed)
# process_all_lts_with_monads(force=True)  # Add monad columns
# clean_all_lts()             # Remove duplicates after creation